
# --------------------
# Global configuration
options:
  local_reference_substitution: true  # NO - SHOULD BE A LIST!

  # list of sources for functions that make us the validation library
  # there's a build in library to start us off, but you (will...not yet) be able to point to github etc
  # to extend capability (i.e for non generic use cases).
  module_sources:
    - /library  # default/built-in


# ------------------------------
# Defining Validation Steps:
checking_rounds:

  basic_structure_linting:
      description: run basic csvlint validation relevant to this dataset
      stop_on_fail: true
      steps:
        - csvlint

  resources_are_accessible:
      description: check that our required sources are valid before we commence more detailed checks
      stop_on_fail: true
      steps:
        - all_http_field_responses_match:
            status_codes: 200
        - all_referenced_json_documents_load:
            follow_children: true
        - all_referenced_csv_files_load:
            follow_children: true

  confirm_csv_resources_exist:
      description: make sure the fields we are specifiying exist in the columns.csvs referenced
      stop_on_fail: true
      steps:
        - assert_all_required_columns_csv_fields_exist

  confirm_resource_integrity:
      description: where we're making use of fields within columns.csv's, confirm the entries are correctly formatted
      stop_on_fail: true
      steps:
        - assert_columns_csv_resources_are_correct
