
# --------------------
# Global configuration
options:

  # list of sources for functions that make us the validation library
  # there's a build in library to start us off, but you (will...not yet) be able to point to github etc
  # to extend capability (i.e for non generic use cases).
  module_sources:
    - /library  # default/built-in


# ------------------------------
# Defining Stages of validation:
stages:

  external_linting_tools:
      execution_order: 1
      description: run basic csvlint validation relevant to this dataset
      stop_on_fail: false
      steps:
        - csvlint

  validate_reference_repos:
      execution_order: 2
      description: confirm format and structure of cogs reference repos
      stop_on_fail: false
      steps:
        - validate_columns_csvs_for_reference_repos_used_by_schema
        - validate_components_csvs_for_reference_repos_used_by_schema
        - validate_codelist_csvs_for_reference_repos_used_by_schema

  cross_validate_reference_data:
      execution_order: 3
      description: confirm that fields that need to match across resources do
      stop_on_fail: false
      steps:
        - compare_components_and_columns_for_reference_repos_used_by_schema
        - compare_components_and_codelist_metadata_for_reference_repos_used_by_schema